server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 10M;

    add_header X-Frame-Options           "SAMEORIGIN"                      always;
    add_header X-Content-Type-Options    "nosniff"                         always;
    add_header X-XSS-Protection          "1; mode=block"                   always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy        "geolocation=(), microphone=()"   always;

    location / {
        limit_req zone=per_ip burst=${NGINX_RATE_BURST} nodelay;

        proxy_pass http://wp-hardened:80;

        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
